package com.blogspot.agusticar.miscuentasv2.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.key.SoftKeyboardInterceptionModifierNode

@Immutable
data class CustomColorsPalette(
    val buttonColorDefault: Color = Color.Unspecified,
    val buttonColorPressed: Color = Color.Unspecified,
    val disableButton:Color = Color.Unspecified,
    val textButtonColorDefault: Color = Color.Unspecified,
    val textButtonColorPressed: Color = Color.Unspecified,
    val backgroundPrimary: Color = Color.Unspecified,
    val backgroundSecondary: Color = Color.Unspecified,
    val barBackground: Color = Color.Unspecified,
    val textColor: Color = Color.Unspecified,
    val invertedTextColor: Color = Color.Unspecified,
    val boldTextColor: Color = Color.Unspecified,
    val barColor: Color = Color.Unspecified,
    val iconInvert: Color = Color.Unspecified,
    val iconColor: Color = Color.Unspecified,
    val contentBarColor:Color = Color.Unspecified,
    val indicatorDefault:Color = Color.Unspecified,
    val indicatorSelected:Color = Color.Unspecified,
    val imageBackground:Color = Color.Unspecified,
    val drawerColor:Color = Color.Unspecified,
    val headDrawerColor:Color = Color.Unspecified,
    val contentDrawerColor:Color = Color.Unspecified,
    val focusedContainerTextField:Color=Color.Unspecified,
    val unfocusedContainerTextField:Color=Color.Unspecified,
    val focusedTextFieldColor:Color=Color.Unspecified,
    val unfocusedTextFieldColor:Color=Color.Unspecified,
    val imageTutorialInit:Color=Color.Unspecified,
    val imageTutorialTarget:Color=Color.Unspecified,
   val rowDrawerPressed:Color=Color.Unspecified,
    val topBarContent:Color = Color.Unspecified,
    val backgroundSwitch:Color = Color.Unspecified,
    val thumbCheckedColor:Color = Color.Unspecified,
    val thumbDefaultColor:Color = Color.Unspecified,
    val trackCheckedColor:Color = Color.Unspecified,
    val trackDefaultColor:Color = Color.Unspecified,
    val textHeadColor:Color = Color.Unspecified,
    val textTransition:Color = Color.Unspecified,
    val buttonTransition:Color = Color.Unspecified,
    val iconCamara:Color = Color.Unspecified,
    val iconIncomeInit:Color = Color.Unspecified,
    val iconIncomeTarget:Color = Color.Unspecified,
    val iconExpenseInit:Color = Color.Unspecified,
    val iconExpenseTarget:Color = Color.Unspecified,
    val incomeColor:Color = Color.Unspecified,
    val expenseColor:Color = Color.Unspecified,
    val initOperatorCalc:Color = Color.Unspecified,
    val targetOperatorCalc:Color = Color.Unspecified,
    val textInitOperatorCalc:Color = Color.Unspecified,
    val textTargetOperatorCalc:Color=Color.Unspecified,
    val initDelCalc:Color = Color.Unspecified,
    val targetDelCalc:Color = Color.Unspecified,
    val numberCalColor:Color = Color.Unspecified,
    val progressBar50:Color = Color.Unspecified,
    val progressBar80:Color = Color.Unspecified,
    val progressBar100:Color = Color.Unspecified

    )

val LightCustomColorsPalette = CustomColorsPalette(
    buttonColorDefault = DarkPeach,
    buttonTransition = BurntPeach,
    buttonColorPressed = BurntPeach,
    disableButton = SoftPeach,
    textButtonColorDefault =  LightYellow,
    textButtonColorPressed =  White,
    backgroundPrimary =  PeachyCream,
    backgroundSecondary =  LightYellow,
    barBackground= DeepTerracotta,
    textColor =  DeepBrown,
    textTransition = White,
    invertedTextColor= LightYellow,
    boldTextColor =  Black,
    iconInvert= LightYellow,
    iconColor = LightYellow,
    contentBarColor = DarkBrown,
    indicatorDefault =  SoftPeach,
    indicatorSelected =  WarmChocolate,
    imageBackground = DeepTerracotta,
    drawerColor = LightYellow,
    headDrawerColor = BurntPeach,
    contentDrawerColor = DarkBrown,
    focusedContainerTextField = LightYellow,
    unfocusedContainerTextField = LightYellow,
    focusedTextFieldColor = DarkBrown,
    unfocusedTextFieldColor = DarkBrown,
    imageTutorialInit = SoftPeach,
    imageTutorialTarget = DarkPeach,
    rowDrawerPressed = BurntPeach,
    topBarContent=LightYellow,
    backgroundSwitch = BurntPeach,
    thumbCheckedColor = DeepTerracotta,
    thumbDefaultColor = SoftPeach,
    trackCheckedColor = SoftPeach,
    trackDefaultColor = DeepTerracotta,
    textHeadColor = Black,
    iconCamara = Black,
    iconIncomeInit = greenLight,
    iconIncomeTarget = darkOliveGreen,
    iconExpenseInit = redDark,
    iconExpenseTarget = redLight,
    incomeColor = greenLight,
    expenseColor = redLight,
    initOperatorCalc = darkOliveGreen,
    targetOperatorCalc = greenLight,
    initDelCalc = redDark,
    targetDelCalc = redLight,
    textInitOperatorCalc = LightYellow,
    textTargetOperatorCalc = White,
    progressBar50 = greenDark,
    progressBar80 = SoftPeach,
    progressBar100 = redDark


)
val DarkCustomColorsPalette = CustomColorsPalette(
    buttonColorDefault =  PeachyCreamTransition,
    buttonColorPressed =  PeachyCream,
    buttonTransition = PeachyCreamTransition,
    disableButton = LightYellow,
    textButtonColorDefault =  DarkBrown,
    textButtonColorPressed =  Black,
    backgroundPrimary =  DarkBrown,
    backgroundSecondary =  MediumDarkBrown,
    barBackground= Black,
    textColor =  LightYellow,
    textTransition = Black,
    invertedTextColor= DarkBrown,
    boldTextColor =  LightYellow,
    iconInvert = LightYellow,
    iconColor = LightYellow,
    contentBarColor = LightYellow,
    indicatorDefault =  PeachyCreamTransition,
    indicatorSelected =  PeachyCream,
    imageBackground = Black,
    drawerColor = MediumDarkBrown,
    headDrawerColor = SoftPeach,
    contentDrawerColor = White,
    focusedContainerTextField = MediumDarkBrown,
    unfocusedContainerTextField = MediumDarkBrown,
    focusedTextFieldColor = LightYellow,
    unfocusedTextFieldColor = LightYellow,
    imageTutorialInit = PeachyCreamTransition,
    imageTutorialTarget = PeachyCream,
    topBarContent=LightYellow,
    rowDrawerPressed = PeachyCream,
    backgroundSwitch = Black,
    thumbCheckedColor = SoftPeach,
    thumbDefaultColor = PeachyCream,
    trackCheckedColor = PeachyCream,
    trackDefaultColor = Black,
    textHeadColor = SoftPeach,
    iconCamara = Black,
    iconIncomeInit = greenPistachio,
    iconIncomeTarget = greenPistachioTransition,
    iconExpenseInit = coralRed,
    iconExpenseTarget = coralRedTransition,
    incomeColor = greenPistachio,
    expenseColor = coralRed,
    initDelCalc = coralRedTransition,
    targetDelCalc = coralRed,
    initOperatorCalc = greenPistachioTransition,
    targetOperatorCalc = greenPistachio,
    textInitOperatorCalc = LightYellow,
    textTargetOperatorCalc = White,
    progressBar50 = greenPistachio,
    progressBar80 = BurntPeach,
    progressBar100 = coralRed
)

val LocalCustomColorsPalette = staticCompositionLocalOf { CustomColorsPalette() }
